language: ruby
before_install: gem install bundler --pre
install:
  - gem update --system
  - bundle update
script: xvfb-run rake
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head

